<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pictures"
 *
 * Auto generated by Extension Builder 2020-02-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Pictures',
    'description' => 'Another gallery extension',
    'category' => 'plugin',
    'author' => 'Andreas Thurnheer-Meier, Daniel Corn',
    'author_email' => 'tma@iresults.li, cod@iresults.li',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
